services:
  # Definition for the "accounts" microservice
  accounts:
    # Specifies the Docker image to use for this service
    image: ilbertca26/accounts:s4 # 'accounts' image with the tag 's4' from the 'ilbertca26' repository
    # Assigns a custom name to the container for easier identification
    container_name: accounts-ms # Container will be named "accounts-ms"
    # Specifies how ports are mapped between the host machine and this container
    ports:
      - 8080:8080 # Maps host port 8080 to container port 8080
    # Deployment configuration for resource limits
    deploy:
      resources:
        limits:
          memory: 700M # Restricts the container to a maximum of 700 MB memory
    # Declares the network this service will participate in
    networks:
      - ilbert-network # Adds the service to the "ilbert-network"

  # Definition for the "loans" microservice
  loans:
    # Specifies the Docker image to use for this service
    image: ilbertca26/loans:s4 # 'loans' image with the tag 's4' from the 'ilbertca26' repository
    # Assigns a custom name to the container for easier identification
    container_name: loans-ms # Container will be named "loans-ms"
    # Specifies how ports are mapped between the host machine and this container
    ports:
      - 8090:8090 # Maps host port 8090 to container port 8090
    # Deployment configuration for resource limits
    deploy:
      resources:
        limits:
          memory: 700M # Restricts the container to a maximum of 700 MB memory
    # Declares the network this service will participate in
    networks:
      - ilbert-network # Adds the service to the "ilbert-network"

  # Definition for the "cards" microservice
  cards:
    # Specifies the Docker image to use for this service
    image: ilbertca26/cards:s4 # 'cards' image with the tag 's4' from the 'ilbertca26' repository
    # Assigns a custom name to the container for easier identification
    container_name: cards-ms # Container will be named "cards-ms"
    # Specifies how ports are mapped between the host machine and this container
    ports:
      - 9000:9000 # Maps host port 9000 to container port 9000
    # Deployment configuration for resource limits
    deploy:
      resources:
        limits:
          memory: 700M # Restricts the container to a maximum of 700 MB memory
    # Declares the network this service will participate in
    networks:
      - ilbert-network # Adds the service to the "ilbert-network"

# Definition of a custom Docker network
networks:
  ilbert-network: # Custom bridge network named "ilbert-network"
    driver: bridge # Uses Docker's 'bridge' network driver to manage container communication
