spring:
  config:
    activate:
      on-profile: prod

build:
  version: "1.0"

accounts:
  message: "Welcome to the Accounts Microservice PROD"
  contactDetails:
    name: "Ilbert Castillo PROD"
    email: "ilbert@gmail.com"
  onCallSupport:
    - (849) 555-8888
    - (849) 555-8888